### OpenAI Source
openai_source: "azure"

### inference model
inference_model_name_or_path: taide/Llama3-TAIDE-LX-8B-Chat-Alpha1
inference_mode: local
cot: true

### checker model
checker_model_name_or_path: Qwen/Qwen2.5-32B-Instruct
check_mode: local

### translation model
translation_model_name_or_path: gpt-4o-mini
translation_mode: api
transation_templates_name: test
source_lang: ko
target_lang: zh-tw

### dataset
task: hae-rae-bench_test  
task_dir: evaluation_data
template: fewshot
lang: ko
n_shot: 0
benchmark_mode: mix
pipeline: diff
batch_size: 4

### output
save_dir: score/hae-rae/diff_lang/pipeline-testing

### VLLM
vllm_maxlen: 8192
vllm_max_concurrency: 100

### debug
testing_size: 5
record_all: true
# print_param_status: false